### ISSUE TITLE
Server Crash: segmentation fault

### ISSUE THREAD

**Issue by MichaelDBA** [cybertec-postgresql/pg_squeeze#9] opened 2018-03-24 13:34 UTC
pg_squeeze caused a segmentation fault using pg_squeeze 1.1 on PG version 10.2.

Here is the log for starting a pg_squeeze worker, insert into squeeze.tables and segmentation fault that resulted:
```
2018-03-24 09:25:38 EDT [8787]: [5-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 8.158 ms  statement: INSERT INTO squeeze.tables (tabschema, tabname, schedule, free_space_extra, vacuum_max_age, max_retry, clustering_index) VALUES ('public', 'sys_order', '{09:26, 23:00}', 10, '1 hours', 0, 'pk_order_id');
2018-03-24 09:25:47 EDT [8787]: [6-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 0.669 ms  statement: SELECT squeeze.start_worker();
2018-03-24 09:26:33 EDT [8787]: [10-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 1.950 ms  statement: select coalesce(datname,'N/A') as datname, pid, coalesce(usename, 'N/A') as usename, substring(application_name, 1,10) as app, wait_event, wait_event_type as we_type, state, backend_type, to_char(backend_start, 'YYYY-MM-DD HH24:MI:SS') as backend_start,  coalesce(to_char(state_change, 'YYYY-MM-DD HH24:MI:SS'), 'N/A') as state_change, coalesce(to_char(query_start, 'YYYY-MM-DD HH24:MI:SS'), 'N/A') as query_start, cast(EXTRACT(EPOCH FROM (now() - backend_start)) as integer) as conn_secs,(case when state <> 'active' then cast(EXTRACT(EPOCH FROM (now() - state_change)) as integer) else -1 end) as idle_secs,(case when state  = 'active' then cast(EXTRACT(EPOCH FROM (now() - query_start)) as integer) else -1 end) as q_secs, coalesce(substring(query,1,30), 'N/A') as query from pg_stat_activity;
2018-03-24 09:26:48 EDT [8831]: [1-1] user=,db=,app=,client= state=00000 LOG:  logical decoding found consistent point at 35/E73D4BF0
2018-03-24 09:26:48 EDT [8831]: [2-1] user=,db=,app=,client= state=00000 DETAIL:  There are no running transactions.
2018-03-24 09:26:48 EDT [8831]: [3-1] user=,db=,app=,client= state=00000 CONTEXT:  SQL statement "SELECT squeeze.squeeze_table(v_tabschema, v_tabname,
         v_cl_index, v_rel_tbsp, v_ind_tbsps, v_autovac, v_autovac_toast)"
        PL/pgSQL function squeeze.process_current_task() line 43 at PERFORM
        SQL statement "SELECT squeeze.process_current_task()"
2018-03-24 09:27:18 EDT [8710]: [7-1] user=,db=,app=,client= state=00000 LOG:  worker process: squeeze worker for database testing (PID 8831) was terminated by signal 11: Segmentation fault
2018-03-24 09:27:18 EDT [8710]: [8-1] user=,db=,app=,client= state=00000 DETAIL:  Failed process was running: SELECT squeeze.process_current_task()
2018-03-24 09:27:18 EDT [8710]: [9-1] user=,db=,app=,client= state=00000 LOG:  terminating any other active server processes
2018-03-24 09:27:18 EDT [8740]: [7-1] user=postgres,db=example,app=mysub,client=127.0.0.1 state=57P02 WARNING:  terminating connection because of crash of another server process
2018-03-24 09:27:18 EDT [8740]: [8-1] user=postgres,db=example,app=mysub,client=127.0.0.1 state=57P02 DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2018-03-24 09:27:18 EDT [8740]: [9-1] user=postgres,db=example,app=mysub,client=127.0.0.1 state=57P02 HINT:  In a moment you should be able to reconnect to the database and repeat your command.
```

**Comment by ahouska** [comment] 2018-03-26 07:44
Thanks for the report!

Are you able to reproduce the error? (If you have enough disk space, please backup the data directory so that you have the original data if the next squeeze succeeds by chance.) 

For repeated attempts, you can run the following commands instead of configuring the schedule and waiting for the worker again and again:

SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
SELECT squeeze.squeeze_table('public', 'sys_order', 'pk_order_id', NULL, NULL, false, false);

And if you still can reproduce the issue: is it difficult for you to generate core dump? Or anonymize the data and share the data directory?

**Comment by MichaelDBA** [comment] 2018-03-27 11:16
I ran the following:
```
testing=# SELECT squeeze.stop_worker();
 stop_worker
-------------
 t
(1 row)

testing=# SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
 set_reloptions
----------------

(1 row)

testing=# SELECT squeeze.squeeze_table('public', 'sys_order', 'pk_order_id', NULL, NULL, false, false);
ERROR:  replication slot "pg_squeeze_slot_16896" already exists
testing=# ERROR:  replication slot "pg_squeeze_slot_16896" already exists

```
Here is the PG log:
```
2018-03-27 07:12:30 EDT [3657]: [5-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 384.043 ms  statement: SELECT squeeze.stop_worker();
2018-03-27 07:12:54 EDT [3657]: [6-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  process 3657 still waiting for AccessExclusiveLock on relation 22167 of database 16896 after 1000.156 ms
2018-03-27 07:12:54 EDT [3657]: [7-1] user=postgres,db=testing,app=psql,client=[local] state=00000 DETAIL:  Process holding the lock: 3749. Wait queue: 3657.
2018-03-27 07:12:54 EDT [3657]: [8-1] user=postgres,db=testing,app=psql,client=[local] state=00000 STATEMENT:  SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
2018-03-27 07:13:12 EDT [3657]: [9-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  process 3657 acquired AccessExclusiveLock on relation 22167 of database 16896 after 19507.317 ms
2018-03-27 07:13:12 EDT [3657]: [10-1] user=postgres,db=testing,app=psql,client=[local] state=00000 STATEMENT:  SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
2018-03-27 07:13:12 EDT [3657]: [11-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 19592.728 ms  statement: SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
2018-03-27 07:13:33 EDT [3657]: [12-1] user=postgres,db=testing,app=psql,client=[local] state=42710 ERROR:  replication slot "pg_squeeze_slot_16896" already exists
2018-03-27 07:13:33 EDT [3657]: [13-1] user=postgres,db=testing,app=psql,client=[local] state=42710 STATEMENT:  SELECT squeeze.squeeze_table('public', 'sys_order', 'pk_order_id', NULL, NULL, false, false);

```

**Comment by MichaelDBA** [comment] 2018-03-27 12:29
I rebooted the server and was able to reproduce the error again (bypassing the previous hanging slot mentioned in the previous log.  Here is the log:
```
2018-03-27 08:16:33 EDT [7741]: [3-1] user=,db=,app=,client= state=00000 CONTEXT:  SQL statement "SELECT squeeze.squeeze_table(v_tabschema, v_tabname,
         v_cl_index, v_rel_tbsp, v_ind_tbsps, v_autovac, v_autovac_toast)"
        PL/pgSQL function squeeze.process_current_task() line 43 at PERFORM
        SQL statement "SELECT squeeze.process_current_task()"
2018-03-27 08:16:39 EDT [6941]: [1-1] user=,db=,app=,client= state=00000 LOG:  checkpoint starting: time
2018-03-27 08:17:03 EDT [6938]: [7-1] user=,db=,app=,client= state=00000 LOG:  worker process: squeeze worker for database testing (PID 7741) was terminated by signal 11: Segmentation fault
2018-03-27 08:17:03 EDT [6938]: [8-1] user=,db=,app=,client= state=00000 DETAIL:  Failed process was running: SELECT squeeze.process_current_task()
2018-03-27 08:17:03 EDT [6938]: [9-1] user=,db=,app=,client= state=00000 LOG:  terminating any other active server processes
```

**Comment by ahouska** [comment] 2018-03-27 13:28
I'm afraid the log alone does not help. I need the core dump.

Your previous message indicates that the pg_squeeze background worker was executing the squeeze_table() function so you could not run it manually at the same time. This conflict can be avoided if you comment out the squeeze.worker_autostart variable in postgresql.conf and restart the instance. And in order to get the core dump, please pass -c to pg_ctl in addition to the other options when starting the instance. Thus you should find "core" file in the data directory after the next crash.

**Comment by MichaelDBA** [comment] 2018-03-27 13:56
I have generated the core file.  All I had to do was restart the server with the -c option and then issue:
`SELECT squeeze.start_worker();`

How do I upload the core file since zipped size is about 500KB?

**Comment by ahouska** [comment] 2018-03-28 10:49
I've temporarily exposed my email address in my Github profile. Can you please publish the core file via dropbox.com (or similar service) and send me a link to the file?

**Comment by MichaelDBA** [comment] 2018-03-28 11:53
I added it to my google drive that I made sharable with your gmail account.  Let me know if you got it OK.

**Comment by ahouska** [comment] 2018-03-29 09:08
The core dump does not seem to provide enough info (e.g. line numbers) and I think this is related to the gdb message "no debugging symbols found". If you're willing to spend some more time on it, please try to build PG from source code:

https://www.postgresql.org/ftp/source/v10.3/
https://www.postgresql.org/docs/current/static/installation.html

Instead of simply ./configure, please run

./configure --enable-debug --enable-cassert

As for pg_squeeze, make sure that the PG_CONFIG variable references this new PG installation (and I suggest "make PG_CONFIG=<the new PG path> clean" before the "make ... install)".

Another thing worth trying is to run the code manually: disable the background worker (as described above) and do not run SELECT squeeze.start_worker(). Instead, run the following commands:

SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
SELECT squeeze.squeeze_table('public', 'sys_order', 'pk_order_id', NULL, NULL, false, false);

If this crashes, try again without the clustering index:

SELECT squeeze.set_reloptions('public', 'sys_order', true, false, false);
SELECT squeeze.squeeze_table('public', 'sys_order', NULL, NULL, NULL, false, false);

The point is that corrupted index might be the issue.

**Comment by MichaelDBA** [comment] 2018-03-29 13:45
OK, I have been able to reproduce the segmentation fault whenever you try to do a vacuum with a clustering index whether it is done through the automatic or manual process.

It works as expected in both the automatic and manual method when no clustering index is specified.

Hence, the segmentation fault is due to the clustering index specification.

**Comment by MichaelDBA** [comment] 2018-03-29 13:57
Here is the sys_order table DDL:
```
testing=# \d sys_order
                                           Table "public.sys_order"
    Column     |           Type           | Collation | Nullable |                   Default
---------------+--------------------------+-----------+----------+---------------------------------------------
 order_id      | integer                  |           | not null | nextval('sys_order_order_id_seq'::regclass)
 product_id    | integer                  |           | not null |
 item_count    | integer                  |           | not null |
 order_dt      | timestamp with time zone |           | not null | now()
 valid_dt      | timestamp with time zone |           |          |
 item_category | character(4)             |           | not null |
 item_desc     | character varying(50)    |           | not null |
 extradata     | numeric                  |           |          | (random() * (1000)::double precision)
Indexes:
    "pk_order_id" PRIMARY KEY, btree (order_id)
    "idx_order_order_dt" btree (order_dt)
    "idx_product_id" btree (product_id, item_category)
```
The table has 10 million rows.  I generate bloat by doing an update on a non-indexed column that affects about a third of the table.  
Size without bloat: 1.9 GB
Size with      bloat: 2.6 GB

**Comment by MichaelDBA** [comment] 2018-03-29 13:58
I am also going to upgrade my PG from 10.2 to 10.3 now and validate my test results above after the minor upgrade.

**Comment by MichaelDBA** [comment] 2018-03-29 14:43
I uploaded the **sys_order** table to my google drive that I shared with you.  Perhaps you can generate the same error if you use the same table?  It's about 500 MB zipped up, 1.5 GB unzipped, a normal non compressed pg_dump sql file.

**Comment by ahouska** [comment] 2018-03-30 08:02
I restored your table but squeeze_table() worked. Of course the dump / restore changes the on-disk layout of the table and its indexes, but since you say that REINDEX does not help, then the problem should not be caused by index storage.

To find out whether the problem is specific to pg_squeeze, or if it's something general regarding index scan, I'm curious what you get if you run the following commands:

SET enable_seqscan TO off;
EXPLAIN ANALYZE VERBOSE SELECT * FROM sys_order ORDER BY order_id;

**Comment by MichaelDBA** [comment] 2018-03-30 13:56
Here is the explain output:

```
 Index Scan using pk_order_id on public.sys_order  (cost=0.43..947592.18 rows=12505054 width=85) (actual time=105.567..92447.871 rows=10000000 loops=1)
   Output: order_id, product_id, item_count, order_dt, valid_dt, item_category, item_desc, extradata
 Planning time: 170.469 ms
 Execution time: 93109.382 ms
(4 rows)

```

**Comment by ahouska** [comment] 2018-04-03 11:57
I was wondering if the EXPLAIN ANALYZE fails. CLUSTER should be even more close to pg_squeeze in the way it fetches rows. Can you please try the following?

SET enable_seqscan TO off;
CLUSTER sys_order USING pk_order_id;

**Comment by MichaelDBA** [comment] 2018-04-03 12:51
It works fine:
```
2018-04-03 08:48:18 EDT [2915]: [3-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 0.153 ms  statement: SET enable_seqscan TO off;
2018-04-03 08:50:27 EDT [2915]: [4-1] user=postgres,db=testing,app=psql,client=[local] state=00000 LOG:  duration: 122982.058 ms  statement: CLUSTER sys_order USING pk_order_id;
```

**Comment by MichaelDBA** [comment] 2018-04-03 14:03
Also, I dumped and reloaded sys_order table as sys_order2 table.  Then executed the following scripts which duplicated the segmentation error, so I don't understand how you are not able to reproduce the error when you loaded my pg_dump file.  I also dropped all other slots to make sure that wasn't causing the problem:
```
SELECT squeeze.set_reloptions('public', 'sys_order2', true, false, false);
SELECT squeeze.squeeze_table('public', 'sys_order2', 'pk_order_id2', NULL, NULL, false, false);
```

**Comment by ahouska** [comment] 2018-04-04 17:45
So the you could squeeze the table immediately after the reload, but the failure occurred again after the UPDATE that introduced the new bloat?

**Comment by MichaelDBA** [comment] 2018-04-04 17:57
Yes, so please do the same update as I did on the dump I gave u.

**Comment by ahouska** [comment] 2018-04-05 12:44
Finally I've got the core dump and the backtrace seems to be identical to that you pasted above! It seems like a memory management issue: PG core memory is freed when only the memory allocated for pg_squeeze should be freed. I'll fix it next week. Thanks a lot for your effort!

**Comment by MichaelDBA** [comment] 2018-04-05 14:51
Sweet! Good Job!

**Comment by ahouska** [comment] 2018-04-09 10:39
Fixed in the master branch. I'll apply the patch to the other branches when preparing the next set of releases.

BTW, the failure can be reproduced with smaller table if maintenance_work_mem is low enough.

**Comment by MichaelDBA** [comment] 2018-08-19 01:04
I have errors compiling against postgresql 10 with the master branch.

wget https://github.com/cybertec-postgresql/pg_squeeze/archive/master.zip
unzip master.zip
cd pg_squeeze-master
export PATH=/usr/lib/postgresql/10/bin:$PATH

```
# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -pie -fno-omit-frame-pointer -fPIC -I. -I./ -I/usr/include/postgresql/10/server -I/usr/include/postgresql/internal -I/usr/include/x86_64-linux-gnu   -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/mit-krb5  -c -o pg_squeeze.o pg_squeeze.c
pg_squeeze.c: In function ‘setup_decoding’:
pg_squeeze.c:863:5: error: ‘LogicalDecodingContext’ has no member named ‘fast_forward’
  ctx->fast_forward = false;
     ^
pg_squeeze.c:880:2: error: too many arguments to function ‘MakeTupleTableSlot’
  dstate->tsslot = MakeTupleTableSlot(dstate->tupdesc_change);
  ^
In file included from /usr/include/postgresql/10/server/utils/tuplestore.h:34:0,
                 from /usr/include/postgresql/10/server/nodes/execnodes.h:28,
                 from pg_squeeze.h:23,
                 from pg_squeeze.c:10:
/usr/include/postgresql/10/server/executor/tuptable.h:142:24: note: declared here
 extern TupleTableSlot *MakeTupleTableSlot(void);
                        ^
pg_squeeze.c: In function ‘perform_initial_load’:
pg_squeeze.c:1894:12: error: too many arguments to function ‘tuplesort_begin_cluster’
            false, false);
            ^
In file included from /usr/include/postgresql/10/server/nodes/execnodes.h:29:0,
                 from pg_squeeze.h:23,
                 from pg_squeeze.c:10:
/usr/include/postgresql/10/server/utils/tuplesort.h:66:24: note: declared here
 extern Tuplesortstate *tuplesort_begin_cluster(TupleDesc tupDesc,
                        ^
pg_squeeze.c: In function ‘create_transient_table’:
pg_squeeze.c:2246:3: error: too many arguments to function ‘heap_create_with_catalog’
   false, false, false, InvalidOid, NULL);
   ^
In file included from pg_squeeze.c:16:0:
/usr/include/postgresql/10/server/catalog/heap.h:54:12: note: declared here
 extern Oid heap_create_with_catalog(const char *relname,
            ^
pg_squeeze.c: In function ‘build_transient_indexes’:
pg_squeeze.c:2394:13: error: ‘INDEX_CREATE_IS_PRIMARY’ undeclared (first use in this function)
    flags |= INDEX_CREATE_IS_PRIMARY;
             ^
pg_squeeze.c:2394:13: note: each undeclared identifier is reported only once for each function it appears in
pg_squeeze.c:2508:12: warning: passing argument 7 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘Oid’ but argument is of type ‘struct IndexInfo *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 8 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘Oid’ but argument is of type ‘struct List *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 9 of ‘index_create’ makes pointer from integer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘Oid *’ but argument is of type ‘Oid’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 10 of ‘index_create’ makes pointer from integer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘Oid *’ but argument is of type ‘Oid’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 11 of ‘index_create’ from incompatible pointer type [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘int16 *’ but argument is of type ‘Oid *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 12 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘Datum’ but argument is of type ‘Oid *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 13 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘bool’ but argument is of type ‘int16 *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: warning: passing argument 19 of ‘index_create’ makes integer from pointer without a cast [enabled by default]
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: expected ‘bool’ but argument is of type ‘void *’
 extern Oid index_create(Relation heapRelation,
            ^
pg_squeeze.c:2508:12: error: too few arguments to function ‘index_create’
            NULL);
            ^
In file included from pg_squeeze.c:17:0:
/usr/include/postgresql/10/server/catalog/index.h:45:12: note: declared here
 extern Oid index_create(Relation heapRelation,
            ^
make: *** [pg_squeeze.o] Error 1
```

**Closed** 2018-08-20 06:13 UTC
